<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#comment</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#startshape-directive</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#include-directive</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#background-directive</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#rule-directive</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#shape-directive</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#rule</string>
			</dict>
		</array>
		<key>repository.background-directive.begin</key>
		<string>\b(Background)</string>
		<key>repository.rule-directive.captures</key>
		<dict>
			<key>1</key>
			<dict>
				<key>name</key>
				<string>keyword.control.rule.cfdg</string>
			</dict>
			<key>2</key>
			<dict>
				<key>name</key>
				<string>constant.numeric.cfdg</string>
			</dict>
		</dict>
		<key>repository.rule-directive.match</key>
		<string>\b(rule)\s++(\d+\.?\d*)?\s*(?=\{|$)</string>
		<key>repository.shape-adjustment-block.patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>(\[)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.unordered-block.begin.cfdg</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=\])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#color-adjustment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#geometry-adjustment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#number</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>(\[)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.ordered-block.begin.cfdg</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=\])</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#color-adjustment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#geometry-adjustment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#number</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>repository.shape-directive</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.shape.cfdg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.shape.definition.cfdg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(shape)\s++([a-zA-Z_][a-zA-Z_\.\d]*+)</string>
		</dict>
		<key>repository.shape-replacement.beginCaptures.1.name</key>
		<string>entity.name.function.shape.cfdg</string>
	</dict>
	<key>deleted</key>
	<array>
		<string>repository.rule-directive.begin</string>
		<string>repository.rule-directive.beginCaptures</string>
		<string>repository.rule-directive.end</string>
		<string>repository.rule-directive.endCaptures</string>
		<string>repository.rule-directive.patterns</string>
	</array>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>8D0EE5A2-FB60-40F8-8D0F-1E1FFB506462</string>
</dict>
</plist>
